### ISSUE TITLE
When direct UCB member checks into Kipp event, approval sent to Kipp

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#155]
As a direct UCB member (i.e. UCB as my partner org), when I checked into a KIPP Academy event the approval was sent to a KIPP Academy admin.

My understanding was that each admin approves their own members events, without any exceptions...

**Comment by drenfr01** [comment]
@ballek could you test this a bit in QA then close it?

**Comment by ballek** [comment]
@drenfr01 I submitted for a KIPP event as test user 1, whose partner affiliation is BMCHP. 
![screen shot 2015-06-17 at 2 28 41 pm](https://cloud.githubusercontent.com/assets/7898004/8215369/642a8804-14fd-11e5-9bc7-aae6781c8dff.png) the approval does indeed go to KIPP. would this be a feature since they can check it against their own sign-in sheets?
