### ISSUE TITLE
figure out why some member-generated events provide a "null" category

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#315]
this is perplexing because members are required to submit the sector of their event (education, health, finance, community). it is affecting data analysis of events!

**Comment by drenfr01** [comment]
@ballek I believe this occurs in the transactions collection, but not in the events collection. correct?

**Comment by drenfr01** [comment]
@ballek Okay, after looking through the code I have a theory and a fix. Basically before we denormalized events into transactions we had a category field that would be filled out for ad-hoc events. When we switched over and moved events into transactions I forgot to add a category field. 

Consequently, for ad-hoc events, the transaction document might have a null category in their events.category field. For these cases, you can just go ahead and use the top-level category field, i.e. "category" rather than "event.category"

If this is annoying for data analysis, I can write up a quick data migration script that will populate event.category for ad-hoc transactions. (which is what will happen in the future with the above code fix)

**Comment by drenfr01** [comment]
looks good on my end, @ballek can you test a bit on your end?
