### ISSUE TITLE
how can we implement spanish characters?  

### ISSUE THREAD

**Issue by ballek** [drenfr01/unionCapital#316]
we're currently getting quite an attractive diamond with a question mark in the middle. aesthetic, but not entirely useful. 
<img width="406" alt="screen shot 2015-11-10 at 12 04 31 pm" src="https://cloud.githubusercontent.com/assets/7898004/11069247/3a8cbf9e-87a3-11e5-8bf3-618d95a460ff.png">

**Comment by drenfr01** [comment]
@ballek Okay, the problem was that our encoding wasn't set to UTF-8, which allows spanish characters. The root problem is the Anglo-centric internet, but that's a problem for another day.

So all new events entered should display spanish characters correctly. The problem is that existing events will not display correctly, so we'll need to manually go in and correct them....

![screen shot 2015-11-14 at 5 08 17 pm](https://cloud.githubusercontent.com/assets/508707/11166063/8397a74c-8af2-11e5-8c1d-b18ce299ec82.png)

**Comment by ballek** [comment]
testeeng! muy bonito @drenfr01, muchas gracias! i'll get around to those correciones de mano....
