### ISSUE TITLE
Please double-check this Auto-approval Rule

### ISSUE THREAD

**Issue by unioncapitalboston** [drenfr01/unionCapital#448]
In Finance Category, FII Monthly Meeting should automatically equal 200 points per hour and automatically process when submitted for two hours or less. Over 2 hours should still come to Admin for approval just like all other events.
That means the Partner Event box needs to be disabled for this event so members don't mistakenly earn 400 points per hour by also selecting Partner Event (which it is). UCB button can still be enable for 50 bonus points. Thanks!
![pastedgraphic-2](https://cloud.githubusercontent.com/assets/7445103/18258799/6a9e37fa-73aa-11e6-8e37-b5ba0e1b323a.png)

**Comment by drewproud** [comment]
@unioncapitalboston what are the criteria to mark this as automatically a partner event?

**Comment by ballek** [comment]
@drewproud this is a one-off thing, it is an event that is ONLY provided by a partner

**Comment by drewproud** [comment]
Forgive me as I shake the rust off here - do we currently have a way of denoting that an event is a partner org event? Or are you saying that every FII Monthly Meeting is a partner event.

**Comment by ballek** [comment]
haha no worries, speedo weddings in Oman tend to have that effect ;)

currently we don't have any way to denote this, but looking at the list of selfie activities, this is really the only one that is a standing partner event that will never be uploaded as a 'pre-listed event'. i can see the case for simply re-designating this activity as "Financial Goal-Setting meeting" and treating it like the rest of events, however, i can also see the case for building out partner activities like this (eg. an asthma prevention program wants to reward the specific habit of vacuuming) but i'll wait for @unioncapitalboston to comment.

**Comment by unioncapitalboston** [comment]
Laura is correct "FII Monthly Meeting" is a partner event and the one and only pre-listed partner event, since they meet at variable times and locations and can't be pre-loaded. Thanks!

**Comment by drewproud** [comment]
Sounds good. So @drenfr01 thoughts on just adding a field to eventCategories collection to denote partner?

**Comment by unioncapitalboston** [comment]
Thanks Crew! Do you think these Rule Fixes will be ready to be pushed this weekend? ... before our members bankrupt us ;)

**Comment by drewproud** [comment]
You bet. Just got back from the DR last night but I'll push changes up on Saturday. Hopefully @drenfr01 will be able to deploy then.

**Comment by unioncapitalboston** [comment]
Ahhhhmazin! Thanks

**Comment by ballek** [comment]
@drewproud hey drewbie, since we had a meeting with a partner today that will result in basically another partner-only selfie activity, i second your idea: adding a field to all selfies events that will identify it as belonging to a specific partner or not (most selfie events will have no allegiances).  

as we have specific events that specific partner organizations want to track (such as FII monthly meetings, or asthma management activities), we can run a check of the member's specified partners against this field. if one of a member's partner org matches the specified partner orgs of the activity, they will receive points automatically. if it does not, then it will have to come to admin for approval. 

in pseudocode:

transactions {
category=FII monthly meeting
adHoc= true
partnerOrg=Family Independence Initiative
}

transactions {
category=Community meeting
adHoc=true
partnerOrg=null (is this the right thing to use?)
}

member1 {
partnerOrg=Family Independence Initiative
}

member2 {
partnerOrg=urbanEdge
}

If member 1 tries to log an FII monthly meeting as a selfie event, they are successful, but if member2 tries to log the same thing, their transaction comes for admin approval. Member1 and Member2 can both log a community meeting, since it does not belong to any specific partner organization. 


thoughts? do i make any inkling of sense?

**Comment by drewproud** [comment]
@ballek the problem here is that a transaction is created from a user and either an event or an event category. Since we can't associate an event category with a partner org (since they are just categories), we would have to create an actual event instead of letting them make a selfie event.

Can we just make FII Monthly Meeting worth 100 points and instruct users to click the partner event button?

**Comment by unioncapitalboston** [comment]
That's totally cool to do - thanks for checking it out!

**Comment by ballek** [comment]
@drewproud 
"Sounds good. So @drenfr01 thoughts on just adding a field to eventCategories collection to denote partner?" 

correct me if i'm wrong- reworking the collection structure of eventCategories would be super heavy lift? can we just add a rule here- certain activities have to come for admin approval no matter what?

**Comment by drewproud** [comment]
@ballek yeah, gave up on that idea. I think the easiest move here is just to cap FII Monthly Meeting at 1 hour max so users only get 100 points plus their button. Sound good?

**Comment by ballek** [comment]
@drewproud it might make sense as we're starting to downplay our partnership with FII, the same would go for "Asthma Management", an event category I've been trying to add. Do you know what I'm doing wrong with regards to Houston and creating new event categories? i can never seem to get it to work!

**Comment by unioncapitalboston** [comment]
This looks great! Thank you for getting them updated! Are they now live on the App?
